DROP SEQUENCE SQ_USR_NO;
DROP TABLE USR;
DROP TABLE USR_JOB;
DROP TABLE COD;
DROP TABLE TRX;
DROP SEQUENCE SQ_FORM_NO;
DROP TABLE FORM;
DROP SEQUENCE SQ_ATTR_NO;
DROP TABLE ATTR;
DROP SEQUENCE SQ_HDR_NO;
DROP TABLE HDR;
DROP SEQUENCE SQ_HDR_DTL_NO;
DROP TABLE HDR_DTL;
DROP SEQUENCE SQ_FLOW_NO;
DROP TABLE FLOW;
DROP SEQUENCE SQ_BBS_NO;
DROP TABLE BBS;
DROP SEQUENCE SQ_BBS_FILE_NO;
DROP TABLE BBS_FILE;

CREATE SEQUENCE SQ_USR_NO START WITH 1;

CREATE TABLE USR (
    USR_NO INT PRIMARY KEY,
    COP_CD VARCHAR2(3) NOT NULL,
    ID  VARCHAR2(32) NOT NULL UNIQUE,
    PIN VARCHAR2(256) NOT NULL,
    NAME VARCHAR2(128) NOT NULL,
    MOBILE VARCHAR2(16),
    ENABLE_SYSTEM VARCHAR2(16) DEFAULT 'NONE' CHECK(ENABLE_SYSTEM IN ('NONE', 'TEST', 'OPERATION', 'ALL')), 
    TYPE VARCHAR2(16) DEFAULT 'GUEST' CHECK (TYPE IN ('SYSOP', 'MANAGER', 'USER', 'GUEST')),
    STATUS VARCHAR2(16) DEFAULT 'REQUEST' CHECK (STATUS IN ('APPROVE', 'REQUEST', 'SLEEP', 'DENY')),
    PIN_ERROR_COUNT NUMBER(2, 0) DEFAULT 0,
    PIN_CHANGED DATE DEFAULT SYSDATE,
    ACCESSED DATE,
    REQUESTED DATE DEFAULT SYSDATE,
    APPROVED DATE
);
INSERT INTO USR (USR_NO, COP_CD, ID, PIN, NAME, ENABLE_SYSTEM, TYPE, STATUS, PIN_ERROR_COUNT, PIN_CHANGED, REQUESTED, APPROVED)
VALUES (0, 'N00', 'admin', '@dm1n1$tr@t0r', '통치자', 'ALL', 'SYSOP', 'APPROVE', 0, SYSDATE, SYSDATE, SYSDATE);


CREATE TABLE USR_JOB (
    USR_NO INT,
    JOB_CD VARCHAR2(128),
    JOB_PCD	VARCHAR2(128) DEFAULT 'JOBS',
    PRIMARY KEY (USR_NO, JOB_CD)
);
INSERT INTO USR_JOB VALUES (0, 'J01', 'JOBS');
INSERT INTO USR_JOB VALUES (0, 'J02', 'JOBS');
INSERT INTO USR_JOB VALUES (0, 'J03', 'JOBS');
INSERT INTO USR_JOB VALUES (0, 'J04', 'JOBS');
INSERT INTO USR_JOB VALUES (0, 'J05', 'JOBS');
INSERT INTO USR_JOB VALUES (0, 'J06', 'JOBS');
INSERT INTO USR_JOB VALUES (0, 'J07', 'JOBS');
INSERT INTO USR_JOB VALUES (0, 'J08', 'JOBS');

CREATE TABLE COD (
    CD VARCHAR2(256) NOT NULL,
    PCD VARCHAR2(128) NOT NULL,
    VAL VARCHAR2(2048),
    DSC VARCHAR2(2048),
    ORD NUMBER(3, 0) DEFAULT 0,
    USE CHAR(1) DEFAULT 'Y' CHECK (USE IN ('Y', 'N')),
    PRIMARY KEY (CD, PCD)
);
INSERT INTO COD   (CD, PCD, VAL, ORD, USE) VALUES   ('LOGIN_POLICY', '-', '로그인정책', 0, 'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('ACCOUNT_EXPIRE', 'LOGIN_POLICY', '90', '사용하지않는 계정 만료기일 ', 0,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('PIN_EXPIRE', 'LOGIN_POLICY', '90', '비밀번호 사용 만료기일', 0,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('PIN_MAX_ERROR', 'LOGIN_POLICY', '5', '비밀번호를 틀려 계정이 잠기기까지의 횟수', 0,     'Y');
INSERT INTO COD   (CD, PCD, VAL, ORD, USE) VALUES   ('CORPS', '-', '손해보험회원사', 0, 'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N00', 'CORPS', '손해보험협회', '손보협회', 0,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N01', 'CORPS', '메리츠화재해상보험', '메리츠', 1,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N02', 'CORPS', '한화손해보험', '한화', 2,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N03', 'CORPS', '롯데손해보험', '롯데', 3,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N04', 'CORPS', 'MG손해보험', 'MG', 4,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N06', 'CORPS', '제일화재해상보험', '제일', 6,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N08', 'CORPS', '삼성화재해상보험', '삼성', 7,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N09', 'CORPS', '현대해상화재보험', '현대', 8,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N10', 'CORPS', 'KB손해보험', 'KB', 9,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N11', 'CORPS', '동부화재해상보험', '동부', 10,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N16', 'CORPS', 'AXA손해보험', 'AXA', 11,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N17', 'CORPS', '더케이손해보험', '더케이', 12,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N51', 'CORPS', 'AIG손해보험', 'AIG', 13,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N66', 'CORPS', 'BNP파리바카디프손해보험', 'BNP', 14,     'Y');
INSERT INTO COD   (CD, PCD, VAL, DSC, ORD, USE) VALUES   ('N71', 'CORPS', '농협손해보험', '농협', 15,     'Y');
INSERT INTO COD   (CD, PCD, VAL, ORD, USE) VALUES   ('JOBS', '-', '업무', 0, 'Y');
INSERT INTO COD   (CD, PCD, VAL, ORD, USE) VALUES   ('J01', 'JOBS', '다중이용업소', 1, 'Y');
INSERT INTO COD   (CD, PCD, VAL, ORD, USE) VALUES   ('J02', 'JOBS', '대리점관리', 2, 'Y');
INSERT INTO COD   (CD, PCD, VAL, ORD, USE) VALUES   ('J03', 'JOBS', '보험가입조회', 3, 'Y');
INSERT INTO COD   (CD, PCD, VAL, ORD, USE) VALUES   ('J04', 'JOBS', '보험다모아', 4, 'Y');
INSERT INTO COD   (CD, PCD, VAL, ORD, USE) VALUES   ('J05', 'JOBS', '설계사관리', 5, 'Y');
INSERT INTO COD   (CD, PCD, VAL, ORD, USE) VALUES   ('J06', 'JOBS', '세금우대', 6, 'Y');
INSERT INTO COD   (CD, PCD, VAL, ORD, USE) VALUES   ('J07', 'JOBS', '퇴직연금', 7, 'Y');
INSERT INTO COD   (CD, PCD, VAL, ORD, USE) VALUES   ('J08', 'JOBS', '휴면보험', 8, 'Y');


CREATE TABLE TRX (
    TRX_NO          INT     PRIMARY KEY,
    TRX_CD          VARCHAR2(32)    UNIQUE,
    TEST_NO            INT                UNIQUE,
    TEST_CD         VARCHAR2(32)    UNIQUE,
    JOB             VARCHAR2(128),
    TYPE            VARCHAR2(8)     DEFAULT 'ONLINE' CHECK (TYPE IN ('ONLINE', 'FILE')),
    HDR_NO          INT,
    DSC             VARCHAR2(2048)
);


CREATE SEQUENCE SQ_FORM_NO START WITH 1;

CREATE TABLE FORM (
    FORM_NO         INT         PRIMARY KEY,
    FORM_CD         VARCHAR2(4),
    WORK_CD         VARCHAR2(3),
    TRX_NO          INT,
    DSC             VARCHAR2(2048),
    DATA_OFFSET     INT,
    REPEAT_LENGTH   INT
);


CREATE SEQUENCE SQ_ATTR_NO START WITH 1;

CREATE TABLE ATTR (
    ATTR_NO     INT PRIMARY KEY,
    NAME        VARCHAR2(128),
    FORM_NO     INT,
    DATA_TYPE   VARCHAR2(16) DEFAULT 'MASKABLE' CHECK (DATA_TYPE IN ('MASKABLE', 'FINDABLE')),
    "OFFSET"    INT,
    LENGTH      INT
);


CREATE SEQUENCE SQ_HDR_NO START WITH 1;

CREATE TABLE HDR (
    HDR_NO      INT PRIMARY KEY,
    NAME        VARCHAR2(128),
    TYPE        VARCHAR2(16) DEFAULT('NORMAL') CHECK (TYPE IN ('NORMAL', 'STANDARD'))
);


CREATE SEQUENCE SQ_HDR_DTL_NO START WITH 1;

CREATE TABLE HDR_DTL (
    HDR_DTL_NO  INT     PRIMARY KEY,
    HDR_NO      INT,
    NAME        VARCHAR2(128),
    TYPE        VARCHAR2(32) DEFAULT('NUMBER') CHECK (TYPE IN ('NUMBER', 'STRING')),
    "OFFSET"    INT,
    LENGTH      INT,
    ORD         INT     DEFAULT 0
);


CREATE SEQUENCE SQ_FLOW_NO START WITH 1;

CREATE TABLE FLOW (
    FLOW_NO     INT PRIMARY KEY,
    JOB         VARCHAR2(128) NOT NULL,
    TRX_NO      INT NOT NULL,
    TYP_NO      INT NOT NULL,
    SND_CORP    VARCHAR2(3),
    RCV_CORP    VARCHAR2(3),
    REPEAT      CHAR(1)     DEFAULT 'N' CHECK (REPEAT IN ('Y', 'N')),
    OMIT        CHAR(1)     DEFAULT 'N' CHECK (OMIT IN ('Y', 'N'))
);


CREATE SEQUENCE SQ_BBS_NO START WITH 1;

CREATE TABLE BBS (
    BBS_NO        INT PRIMARY KEY,
    USR_NO        INT NOT NULL,
    GRP			  VARCHAR2(16) DEFAULT 'TALKATIVE' CHECK (GRP IN ('NOTICE', 'DESIGN', 'TALKATIVE')),
    JOB         VARCHAR2(128),
    TITLE        VARCHAR2(512) NOT NULL,
    TEXT        CLOB,
    READ        INT,
    CREATED        DATE DEFAULT SYSDATE,
    UPDATED        DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SQ_BBS_FILE_NO START WITH 1;

CREATE TABLE BBS_FILE (
    BBS_FILE_NO    INT PRIMARY KEY,
    BBS_NO        INT NOT NULL,
    UUID            VARCHAR2(16)    UNIQUE,
    PATH        VARCHAR2(512)    NOT NULL,
    NAME        VARCHAR2(256)    NOT NULL,
    MIME        VARCHAR2(128),
    LENGTH        INT
);