CREATE SEQUENCE SQ_USR_UID START WITH 1;

CREATE TABLE USR (
    NO INT PRIMARY KEY,
    GRPCD VARCHAR2(32) NOT NULL,
    ID  VARCHAR2(32) NOT NULL UNIQUE,
    PIN VARCHAR2(256) NOT NULL,
    NAME VARCHAR2(128) NOT NULL,
    MOBILE VARCHAR2(16),
    STATUS VARCHAR2(16) DEFAULT 'REQUESTED' CHECK (STATUS IN ('APPROVED', 'REQUESTED', 'SLEEP', 'DENY')),
    TYPE VARCHAR2(16) DEFAULT 'USER' CHECK (TYPE IN ('SYSOP', 'OPERATOR', 'USER')),
    ACCESS_ERROR_COUNT NUMBER(2, 0),
    ACCESSED DATE,
    REQUESTED DATE DEFAULT SYSDATE,
    APPROVED DATE,
    UPDATED DATE DEFAULT SYSDATE
);

CREATE TABLE GRP (
    GRPCD VARCHAR2(32),
    NAME VARCHAR2(128),
    ORD INT,
    ENABLE CHAR(1) CHECK (ENABLE IN ('Y', 'N')),
    PRIMARY KEY(GRPCD) 
);